### ISSUE TITLE
Firefly Application should say App Builder application in graphic

### ISSUE THREAD

**Issue by gribbletog** [AdobeDocs/uix#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://developer-stage.adobe.com/uix/docs/getting-started/app-builder/#what-is-app-builder

### What's wrong with the content?

Text is all about App Builder, but the graphic on page says App Builder application. The graphic should change this to App Builder application. Firefly was the pre-release code name for App Builder and should not be used unless talking about Adobe Firefly, our generative AI solution.

### What changes do you propose?

Please update the graphic to rename the box Firefly application to App Builder application.

### Anything else that can help to cover this?

that's it.

**Comment by fe-lix-** [comment]
Finally done.
